config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :forums do
    resources :comments
  end

  resources :portfolios
  resources :securities
  resources :markets
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :forum
end

app/models/forum.rb
class Forum < ApplicationRecord
  has_many :comment
end

app/models/market.rb
class Market < ApplicationRecord
  has_many :security
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  has_many :security
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnare
  has_many :answer
end

app/models/questionnare.rb
class Questionnare < ApplicationRecord
  belongs_to :user
  has_many :question
end

app/models/security.rb
class Security < ApplicationRecord
  belongs_to :portfolio
  belongs_to :market
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @forum = Forum.find(params[:forum_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @forum = Forum.find(params[:forum_id])
    @comment.forum = @forum
    @comment.user = current_user
    if @comment.save
      redirect_to forums_path(@forum)
    else
      redirect_to new_forum_comment_path
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    #@comment.update(comment_params)
    @comment.forum = @forum
    redirect_to forums_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to forums_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user, :forum)
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
  end

  def forum_id
    @forum = Forum.find(params[:id])
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = Market.all
  end

  def show
    @market = Market.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :portfolio_set, only: [:show, :edit, :update]

  def show; end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to portfolio_path(@portfolio)
    else
      redirect_to new_portfolio_path
    end

  end

  def edit; end

  def update
  end

  private

  def portfolio_set
    @portfolio = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:name, :value, :settlement_value, :settlement_date)
  end
end

app/controllers/securities_controller.rb
class SecuritiesController < ApplicationController
  def index
    @securities = Security.all
  end

  def show
    @security = Security.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/comments/edit.html.erb
<%= render 'shared/form' %>

app/views/comments/new.html.erb
<%= render 'shared/form' %>

app/views/comments/show.html.erb
<p><%= @comment.content %></p>
<p><%= @comment.user.email %></p>

<div>
  <%= link_to 'Edit Comment', edit_forum_comment_path %>
</div>

app/views/forums/index.html.erb
<h2>Forums List</h2>
<ul>
  <% @forums.each do |forum| %>
  <li><%=link_to forum.name, forum_path(forum) %></li>
  <% end  %>
</ul>

app/views/forums/show.html.erb
<h2><%= @forum.name %></h2>
<% @forum.comment.each do |comment| %>
<ol>
  <li><%= comment.content %></li>
  <li><%= comment.user.email %></li>
  <li><%= link_to 'See full content', forum_comment_path(@forum) %></li>
</ol>
<% end %>

<div>
  <%= link_to "Create a new comment", new_forum_comment_path(@forum) %>
</div>

app/views/markets/index.html.erb
<% @markets.each do |market| %>
<%= market.description %>
<%= market.ytd_return.round(2) %>
<% end  %>

app/views/markets/show.html.erb
<p><%= @market.description %></p>
<p><%= @market.ytd_return %></p>

app/views/portfolios/new.html.erb
<%= simple_form_for(@portfolio) do |f| %>
<%= f.input :name %>
<%= f.submit %>
<% end %>

app/views/portfolios/show.html.erb
<h3>Portfolio: <%= @portfolio.name %></h3>
<p> Settlement Value:<%= @portfolio.settlement_value %></p>
<p> Portfolio Value:<%= @portfolio.value %></p>
<p><%= "Absolute return: #{(@portfolio.value/@portfolio.settlement_value-1)*100}%" %></p>
<p><%= @portfolio. %></p>

app/views/securities/index.html.erb
<div>
  <h2>Security</h2>
  <% @securities.each do |security| %>
  <p><strong>Description:</strong> <%= security.description %></p>
  <p><strong>Security Type: </strong><%= security.security_type.capitalize %></p>
  <% end %>
</div>

app/views/securities/show.html.erb
<p><%= @security.description %></p>
<p><%= link_to "#{@security.market.description}",  %></p>